name: Windows Engine Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Generate solution with Premake
      run: |
        Emu/external/premake/premake5.exe --tests vs2022

    - name: Build EmuTests (Debug x64)
      run: |
        msbuild EMUEngine.sln /t:EmuTests /p:Configuration=Debug /p:Platform=x64 /m


    - name: Run EmuTests
      run: |
        .\bin\Debug-x64\EmuTests\EmuTests.exe --gtest_color=yes
